export const translations = {
  en: {
    title: "Test Your Knowledge",
    headerSubtitle: "An AI-powered quiz with a focus on the MENA region",
    subtitle: "Challenge yourself with an AI-powered quiz! Choose your topics and answer 20 questions generated just for you by Gemini, with a focus on the MENA region.",
    startGame: "Start Game",
    chooseCategory: "Choose Your Topics",
    chooseDifficulty: "Choose a Difficulty",
    category: "Topics",
    backToCategories: "← Back to Topics",
    continue: "Continue",
    selectAtLeastOne: "Please select at least one sub-category.",
    question: "Question",
    of: "/",
    nextQuestion: "Next Question",
    finishQuiz: "Finish Quiz",
    skipWithCount: (count: number) => `Skip (${count})`,
    skippedQuestion: "You skipped this question.",
    quizComplete: "Quiz Complete!",
    resultsSubtitle: "Here's how you did:",
    correctAnswers: (score: number, total: number) => `You answered ${score} out of ${total} questions correctly.`,
    playAgain: "Play Again",
    backToDashboard: "Back to Dashboard",
    reviewAnswers: "Review Your Answers",
    yourAnswer: "Your answer",
    correctAnswer: "Correct answer",
    loadingMessage: (difficulty: string, category: string) => `Generating ${difficulty} Quiz on ${category}...`,
    loadingSubmessage: "Focusing on the MENA region. This may take a moment...",
    errorTitle: "An Error Occurred",
    tryAgain: "Try Again",
    selectLanguage: "Select a Language",
    auth: {
      signInTitle: "Sign In",
      signUpTitle: "Create Account",
      nameLabel: "Name",
      emailLabel: "Email",
      passwordLabel: "Password",
      signInButton: "Sign In",
      signUpButton: "Sign Up",
      noAccountPrompt: "Don't have an account?",
      hasAccountPrompt: "Already have an account?",
      signUpLink: "Sign up",
      signInLink: "Sign in",
      loading: "Loading...",
      nameRequired: "Name is required for sign up.",
      unknownError: "An unknown error occurred.",
    },
    dashboard: {
      welcome: (name: string) => `Welcome back, ${name}!`,
      subtitle: "Ready for your next challenge?",
      startNewQuiz: "Start New Quiz",
      logout: "Logout",
      quizHistory: "Quiz History",
      noHistory: "You haven't completed any quizzes yet. Start one to see your history!",
    },
    categories: [
      { name: "History", subcategories: ["Ancient MENA Civilizations", "Islamic Golden Age", "Ottoman Empire", "Modern Middle East"] },
      { name: "Geography", subcategories: ["MENA Capitals & Cities", "Landmarks & Monuments", "Rivers & Deserts", "Regional Geopolitics"] },
      { name: "Art & Culture", subcategories: ["Islamic Architecture", "MENA Cinema & Music", "Cuisine & Traditions", "Festivals & Events"] },
      { name: "Science & Innovation", subcategories: ["Historical Arab Scientists", "Modern Tech in MENA", "Astronomy & Mathematics", "Medicine & Biology"] },
      { name: "Economy & Business", subcategories: ["Oil & Energy Sector", "Major Regional Companies", "Tourism & Hospitality", "Financial Hubs"] },
      { name: "Politics & Governance", subcategories: ["Modern Governments", "Historical Leaders", "Political Movements", "International Relations"] },
      { name: "Religion & Philosophy", subcategories: ["Pillars of Islam", "Regional Mythologies", "Major Religious Sites", "Islamic Scholars"] },
      { name: "Sports", subcategories: ["Famous Football Clubs", "Popular Regional Sports", "MENA in the Olympics", "Major Tournaments"] },
      { name: "Language & Literature", subcategories: ["Arabic Dialects", "Famous Poets & Writers", "Calligraphy Styles", "Pre-Islamic Literature"] },
      { name: "Technology", subcategories: ["Cloud Computing", "JavaScript", "Python", "Artificial Intelligence", "Cybersecurity", "DevOps"] },
      { name: "General Knowledge", subcategories: ["Famous Personalities", "Mythology & Folklore", "Current Events", "Health & Society"] },
    ],
    difficulties: ["Easy", "Medium", "Hard"],
  },
  ar: {
    title: "اختبر معلوماتك",
    headerSubtitle: "اختبار مدعوم بالذكاء الاصطناعي مع التركيز على منطقة الشرق الأوسط وشمال إفريقيا",
    subtitle: "تحدَّ نفسك في اختبار مدعوم بالذكاء الاصطناعي! اختر مواضيعك وأجب على 20 سؤالاً تم إنشاؤها لك بواسطة Gemini، مع التركيز على منطقة الشرق الأوسط وشمال إفريقيا.",
    startGame: "ابدأ اللعبة",
    chooseCategory: "اختر مواضيعك",
    chooseDifficulty: "اختر مستوى الصعوبة",
    category: "المواضيع",
    backToCategories: "→ العودة إلى المواضيع",
    continue: "متابعة",
    selectAtLeastOne: "يرجى اختيار فئة فرعية واحدة على الأقل.",
    question: "سؤال",
    of: "/",
    nextQuestion: "السؤال التالي",
    finishQuiz: "إنهاء الاختبار",
    skipWithCount: (count: number) => `تخط (${count})`,
    skippedQuestion: "لقد تخطيت هذا السؤال.",
    quizComplete: "اكتمل الاختبار!",
    resultsSubtitle: "إليك نتيجتك:",
    correctAnswers: (score: number, total: number) => `لقد أجبت بشكل صحيح على ${score} من أصل ${total} أسئلة.`,
    playAgain: "العب مرة أخرى",
    backToDashboard: "العودة للوحة التحكم",
    reviewAnswers: "مراجعة إجاباتك",
    yourAnswer: "إجابتك",
    correctAnswer: "الإجابة الصحيحة",
    loadingMessage: (difficulty: string, category: string) => `جاري إنشاء اختبار ${difficulty} حول ${category}...`,
    loadingSubmessage: "بالتركيز على منطقة الشرق الأوسط وشمال إفريقيا. قد يستغرق هذا بعض الوقت...",
    errorTitle: "حدث خطأ",
    tryAgain: "حاول مرة أخرى",
    selectLanguage: "اختر لغة",
    auth: {
      signInTitle: "تسجيل الدخول",
      signUpTitle: "إنشاء حساب",
      nameLabel: "الاسم",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      signInButton: "تسجيل الدخول",
      signUpButton: "إنشاء حساب",
      noAccountPrompt: "ليس لديك حساب؟",
      hasAccountPrompt: "لديك حساب بالفعل؟",
      signUpLink: "أنشئ حسابًا",
      signInLink: "سجّل الدخول",
      loading: "جاري التحميل...",
      nameRequired: "الاسم مطلوب لإنشاء حساب.",
      unknownError: "حدث خطأ غير معروف.",
    },
    dashboard: {
      welcome: (name: string) => `مرحبًا بعودتك، ${name}!`,
      subtitle: "هل أنت مستعد للتحدي التالي؟",
      startNewQuiz: "ابدأ اختبارًا جديدًا",
      logout: "تسجيل الخروج",
      quizHistory: "سجل الاختبارات",
      noHistory: "لم تكمل أي اختبارات بعد. ابدأ واحدًا لرؤية سجلك!",
    },
    categories: [
      { name: "التاريخ", subcategories: ["حضارات الشرق الأوسط القديمة", "العصر الذهبي للإسلام", "الدولة العثمانية", "الشرق الأوسط الحديث"] },
      { name: "الجغرافيا", subcategories: ["عواصم ومدن المنطقة", "معالم وآثار", "أنهار وصحاري", "الجغرافيا السياسية الإقليمية"] },
      { name: "الفن والثقافة", subcategories: ["العمارة الإسلامية", "سينما وموسيقى المنطقة", "المطبخ والتقاليد", "مهرجانات ومناسبات"] },
      { name: "العلوم والابتكار", subcategories: ["علماء عرب تاريخيون", "التكنولوجيا الحديثة في المنطقة", "الفلك والرياضيات", "الطب والأحياء"] },
      { name: "الاقتصاد والأعمال", subcategories: ["قطاع النفط والطاقة", "شركات إقليمية كبرى", "السياحة والضيافة", "المراكز المالية"] },
      { name: "السياسة والحكم", subcategories: ["الحكومات الحديثة", "قادة تاريخيون", "الحركات السياسية", "العلاقات الدولية"] },
      { name: "الدين والفلسفة", subcategories: ["أركان الإسلام", "أساطير المنطقة", "مواقع دينية كبرى", "علماء ومفكرون إسلاميون"] },
      { name: "الرياضة", subcategories: ["أندية كرة قدم شهيرة", "رياضات شعبية إقليمية", "المنطقة في الأولمبياد", "بطولات كبرى"] },
      { name: "اللغة والأدب", subcategories: ["اللهجات العربية", "شعراء وكتاب مشهورون", "أنماط الخط العربي", "أدب ما قبل الإسلام"] },
      { name: "التكنولوجيا", subcategories: ["الحوسبة السحابية", "جافاسكريبت", "بايثون", "الذكاء الاصطناعي", "الأمن السيبراني", "DevOps"] },
      { name: "معلومات عامة", subcategories: ["شخصيات مشهورة", "الأساطير والفولكلور", "الأحداث الجارية", "الصحة والمجتمع"] },
    ],
    difficulties: ["سهل", "متوسط", "صعب"],
  },
};