export const translations = {
  en: {
    title: "Test Your Knowledge",
    subtitle: "Challenge yourself with an AI-powered quiz! Choose your topics and answer 20 questions generated just for you by Gemini, with a focus on the MENA region.",
    startGame: "Start Game",
    chooseCategory: "Choose Your Topics",
    chooseDifficulty: "Choose a Difficulty",
    category: "Topics",
    backToCategories: "← Back to Topics",
    continue: "Continue",
    selectAtLeastOne: "Please select at least one sub-category.",
    question: "Question",
    of: "/",
    nextQuestion: "Next Question",
    finishQuiz: "Finish Quiz",
    quizComplete: "Quiz Complete!",
    resultsSubtitle: "Here's how you did:",
    correctAnswers: (score: number, total: number) => `You answered ${score} out of ${total} questions correctly.`,
    playAgain: "Play Again",
    reviewAnswers: "Review Your Answers",
    yourAnswer: "Your answer",
    correctAnswer: "Correct answer",
    loadingMessage: (difficulty: string, category: string) => `Generating ${difficulty} Quiz on ${category}...`,
    loadingSubmessage: "Focusing on the MENA region. This may take a moment...",
    errorTitle: "An Error Occurred",
    tryAgain: "Try Again",
    selectLanguage: "Select a Language",
    categories: [
      { name: "History", subcategories: ["Ancient MENA Civilizations", "Islamic Golden Age", "Ottoman Empire", "Modern Middle East"] },
      { name: "Geography", subcategories: ["MENA Capitals & Cities", "Landmarks & Monuments", "Rivers & Deserts", "Regional Geopolitics"] },
      { name: "Art & Culture", subcategories: ["Arabic Literature & Poetry", "Islamic Architecture", "MENA Cinema & Music", "Cuisine & Traditions"] },
      { name: "Science & Innovation", subcategories: ["Historical Arab Scientists", "Modern Tech in MENA", "Astronomy & Mathematics", "Medicine & Biology"] },
      { name: "General Knowledge", subcategories: ["Sports in MENA", "Mythology & Folklore", "Famous Personalities", "Current Events"] },
    ],
    difficulties: ["Easy", "Medium", "Hard"],
  },
  ar: {
    title: "اختبر معلوماتك",
    subtitle: "تحدَّ نفسك في اختبار مدعوم بالذكاء الاصطناعي! اختر مواضيعك وأجب على 20 سؤالاً تم إنشاؤها لك بواسطة Gemini، مع التركيز على منطقة الشرق الأوسط وشمال إفريقيا.",
    startGame: "ابدأ اللعبة",
    chooseCategory: "اختر مواضيعك",
    chooseDifficulty: "اختر مستوى الصعوبة",
    category: "المواضيع",
    backToCategories: "→ العودة إلى المواضيع",
    continue: "متابعة",
    selectAtLeastOne: "يرجى اختيار فئة فرعية واحدة على الأقل.",
    question: "سؤال",
    of: "/",
    nextQuestion: "السؤال التالي",
    finishQuiz: "إنهاء الاختبار",
    quizComplete: "اكتمل الاختبار!",
    resultsSubtitle: "إليك نتيجتك:",
    correctAnswers: (score: number, total: number) => `لقد أجبت بشكل صحيح على ${score} من أصل ${total} أسئلة.`,
    playAgain: "العب مرة أخرى",
    reviewAnswers: "مراجعة إجاباتك",
    yourAnswer: "إجابتك",
    correctAnswer: "الإجابة الصحيحة",
    loadingMessage: (difficulty: string, category: string) => `جاري إنشاء اختبار ${difficulty} حول ${category}...`,
    loadingSubmessage: "بالتركيز على منطقة الشرق الأوسط وشمال إفريقيا. قد يستغرق هذا بعض الوقت...",
    errorTitle: "حدث خطأ",
    tryAgain: "حاول مرة أخرى",
    selectLanguage: "اختر لغة",
    categories: [
      { name: "التاريخ", subcategories: ["حضارات الشرق الأوسط القديمة", "العصر الذهبي للإسلام", "الدولة العثمانية", "الشرق الأوسط الحديث"] },
      { name: "الجغرافيا", subcategories: ["عواصم ومدن المنطقة", "معالم وآثار", "أنهار وصحاري", "الجغرافيا السياسية الإقليمية"] },
      { name: "الفن والثقافة", subcategories: ["الأدب والشعر العربي", "العمارة الإسلامية", "سينما وموسيقى المنطقة", "المطبخ والتقاليد"] },
      { name: "العلوم والابتكار", subcategories: ["علماء عرب تاريخيون", "التكنولوجيا الحديثة في المنطقة", "الفلك والرياضيات", "الطب والأحياء"] },
      { name: "معلومات عامة", subcategories: ["الرياضة في المنطقة", "الأساطير والفولكلور", "شخصيات مشهورة", "الأحداث الجارية"] },
    ],
    difficulties: ["سهل", "متوسط", "صعب"],
  },
};
